package com.num.tab;
// Generated 2014-2-25 13:40:17 by Hibernate Tools 3.2.1.GA



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer id;
     private int stuId;
     private int teaId;
     private String stuName;
     private String stuTel;

    public Student() {
    }

	
    public Student(int stuId, int teaId, String stuName) {
        this.stuId = stuId;
        this.teaId = teaId;
        this.stuName = stuName;
    }
    public Student(int stuId, int teaId, String stuName, String stuTel) {
       this.stuId = stuId;
       this.teaId = teaId;
       this.stuName = stuName;
       this.stuTel = stuTel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStuId() {
        return this.stuId;
    }
    
    public void setStuId(int stuId) {
        this.stuId = stuId;
    }
    public int getTeaId() {
        return this.teaId;
    }
    
    public void setTeaId(int teaId) {
        this.teaId = teaId;
    }
    public String getStuName() {
        return this.stuName;
    }
    
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }
    public String getStuTel() {
        return this.stuTel;
    }
    
    public void setStuTel(String stuTel) {
        this.stuTel = stuTel;
    }




}


