package tab;
// Generated 2014-2-24 14:48:32 by Hibernate Tools 3.2.1.GA



/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private Integer id;
     private int teaId;
     private String teaName;
     private String teaTel;

    public Teacher() {
    }

	
    public Teacher(int teaId, String teaName) {
        this.teaId = teaId;
        this.teaName = teaName;
    }
    public Teacher(int teaId, String teaName, String teaTel) {
       this.teaId = teaId;
       this.teaName = teaName;
       this.teaTel = teaTel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTeaId() {
        return this.teaId;
    }
    
    public void setTeaId(int teaId) {
        this.teaId = teaId;
    }
    public String getTeaName() {
        return this.teaName;
    }
    
    public void setTeaName(String teaName) {
        this.teaName = teaName;
    }
    public String getTeaTel() {
        return this.teaTel;
    }
    
    public void setTeaTel(String teaTel) {
        this.teaTel = teaTel;
    }




}


